/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    PayrollEscrow: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "function",
          name: "companies",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "hrWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "companyName",
              type: "string",
              internalType: "string",
            },
            {
              name: "escrowBalance",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "confirmTermination",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "depositToEscrow",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "employees",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "employeeAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "monthlySalary",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "startDate",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "lastPaymentDate",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "terminationInitiated",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "initiatedBy",
              type: "address",
              internalType: "address",
            },
            {
              name: "terminationDate",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hireEmployee",
          inputs: [
            {
              name: "_employeeAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_monthlySalary",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "initiateTermination",
          inputs: [
            {
              name: "_employee",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "paySalary",
          inputs: [
            {
              name: "_employee",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerCompany",
          inputs: [
            {
              name: "_companyName",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "EmployeeHired",
          inputs: [
            {
              name: "company",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "employee",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "salary",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SalaryPaid",
          inputs: [
            {
              name: "employee",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TerminationConfirmed",
          inputs: [
            {
              name: "employee",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "severancePaid",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TerminationInitiated",
          inputs: [
            {
              name: "initiator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "employee",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
